### ISSUE TITLE
--f and --force bug parsing

### ISSUE THREAD

**Issue by BehindTheBrain** [redkyn/assigner#108]
assigner assign -f  /// this short version works well.
--force produces a bug that says something like "orce" , presumably due to some kind of argument parsing issue.

**Comment by LinuxMercedes** [comment]
I'm having trouble reproducing this -- would you be able to provide the exact command you ran and the output it gives?

**Comment by BehindTheBrain** [comment]
This seemed to be a local problem for me. It repeated when I tried it 4-5 times on my machine until a restart yesterday... Today, I can't reproduce.
