### ISSUE TITLE
Add an error message to a "master" of a group if they try to run "assigner assign --force" to recreate assigned repositories

### ISSUE THREAD

**Issue by DrDougPhD** [redkyn/assigner#123]
We ran into a problem tonight where a TA could not forcefully recreate assigned repositories. For example, on `lab03`, the TA accidentally instantiated the wrong repository to 26 students. When the TA tried to rectify this by executing the following on the right repository:

    assigner assign -f lab03 --branches master whitespace

the TA was yelled the following by assigner:

    ERROR    403 Client Error: Forbidden for url: https://.../

Although we are not certain, we suspect this error is due to the TA having a "master" role on their group, and not an "owner" role. This will need to be verified at a later time.

More details will follow once we are not in the middle of class :)

**Comment by DrDougPhD** [comment]
I have just confirmed that a `--force` will work if the executor is an owner of a group, but `--force` will not work if the executor is a master. I will now try to isolate where in the code this error comes from (and where a try / except clause should be added).

**Comment by LinuxMercedes** [comment]
It's probably happening on [assign.py line 78](https://github.com/redkyn/assigner/blob/master/assigner/commands/assign.py#L78). Gitlab's docs are ambiguous on this point, but some empirical testing (i.e., I looked in the web UI) shows that Masters aren't allowed to delete group repositories.

**Comment by LinuxMercedes** [comment]
For now I think we'll just document this (see #124) and address the exception later as part of work on #8.

If you run across other bugs like this please let us know! Gitlab's API docs are not very detailed, so it is something of a challenge to know what sort of situations we need to be able to handle.
