### ISSUE TITLE
Deal with students team

### ISSUE THREAD

**Issue by fbab** [redkyn/assigner#126]
Hello,

Congratulations for the work, it looks great.

I would like to suggest a new feature, while trying to migrate from GithubClassroom to Gitlab
Right now, as far as I understood, only individuals can work on an assignment on Assigner
I miss a feature that would allow several students (organised by teams) to work on the same assignment.
Do you see any technical reason that would make it difficult to add in Assigner ?

Thx, Fred.

**Comment by LinuxMercedes** [comment]
Hi Fred,

We've been planning on adding this feature for a while: see #39. There aren't any major technical issues in the way that I'm aware of. If you have any input on what features you'd like to see for group projects, we'd be glad to hear them!

--Nat

**Comment by LinuxMercedes** [comment]
(I'm going to close this issue since #39 already covers this)
