### ISSUE TITLE
Retry with backoff for Gitlab API and git operations

### ISSUE THREAD

**Issue by LinuxMercedes** [redkyn/assigner#127]
It seems that Gitlab can sometimes fall over under a barrage of requests. We've not had much luck getting Gitlab to be more reliable, so we should work around that in Assigner by retrying operations if they fail.

- Delineate between an actual failure and something worth retrying
- Offer some way for the user to specify the max number of retries
- Exponential backoff

**Comment by BehindTheBrain** [comment]
For someone who had this issue with assigner (but tested timeouts in custom git-python scripts), 1.5 to 2.5 seconds fixed delay seems to work most of the time for avoidance.
