### ISSUE TITLE
add a trick to docs or --help for "commit"

### ISSUE THREAD

**Issue by BehindTheBrain** [redkyn/assigner#138]
```
assigner commit assignment-n "message" -a "*" 
assigner commit assignment-n "message" -a '*'
```
Add all the extra stuff dumped in the repos, in my case, often by an auto-grader giving feedback files. 
Note: this works great, but took me a while to figure out, and had puzzled my graders. 

Relates to feature: #98

**Comment by LinuxMercedes** [comment]
Thanks! I've added that to the [tutorial docs for commit](https://github.com/redkyn/assigner/blob/f8f1c0728653b323fb99d2acdf2d718ea1791356/TUTORIAL.md#committing-and-pushing-changes-to-student-repositories). If you want to look over those docs and make sure they aren't missing any other tips from your experience, I'd appreciate it!
