### ISSUE TITLE
`assigner status` command

### ISSUE THREAD

**Issue by LinuxMercedes** [redkyn/assigner#14]
From Ty on IRC:

> I know it would be awesome if it would print out a list of all the repos for a given HW assignment and whether or not they have pushed code.  
> That could be the verbose mode for it.  
> The default behavior could just print out a percentage.  
> I.e., "78% of students have pushed code for assignment 2"
> 
> `assigner status`
> shows percentages for all homework assignments.  Percent on-time, percent late.
> 
> `assigner status 1`
> shows percentages for just homework 1.
> 
> `assigner -v status 1`
> lists all student repos for hw 1 and then whether or not they've pushed something
> 
> Something along those lines

**Comment by michaelwisely** [comment]
I guess this can probably compare the latest commit on a student's `master`  branch to the latest commit to `master` on the base repo, at least. That would give an idea who's pushed anything now.
