### ISSUE TITLE
ERROR 'latin-1' codec can't encode characters in position 9-10: ordinal not in range(256)

### ISSUE THREAD

**Issue by gosnmic** [redkyn/assigner#144]
I was trying to run status on a newly created, assigned, and opened homework and ran into this:
ERROR    time data '2020-03-05T15:22:06.119-06:0-0000' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

Wondering if maybe the response was being formatted slightly differently than before. Running Assigner 1.2.0 on Campus Linux machine... (assign and open seemed to work correctly).

**Comment by gosnmic** [comment]
Oh - shame on you for changing the code in the last day and not telling me :P
Got updated:
Assigner version 2.0.0
UM-AD\mrghx4@rc01ucs213:~/myGit/2020SP$ assigner status hwGit
INFO     Migrating configuration from version 1 to version 2.
ERROR    'latin-1' codec can't encode characters in position 9-10: ordinal not in range(256)


UM-AD\mrghx4@rc01ucs213:~/myGit/2020SP$ assigner status hwGit
ERROR    'latin-1' codec can't encode characters in position 9-10: ordinal not in range(256)

**Comment by LinuxMercedes** [comment]
Encoding error has been [reported upstream](https://github.com/Rockhopper-Technologies/enlighten/issues/13); once they decide what they intend to do we'll either update to their fixed version or use a work-around.

**Comment by BehindTheBrain** [comment]
Looks like we might need to re-open this one:


$ assigner status pa00-env-io
ERROR    time data '2020-09-03T01:03:55.4590' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
