### ISSUE TITLE
assigner status ERROR time data does not match format

### ISSUE THREAD

**Issue by BehindTheBrain** [redkyn/assigner#148]
#144 seems to have popped up again? I didn't see any change to the assigner codebase itself last time, but just a change to the version of enlighten?

$ assigner status pa00-env-io
ERROR    time data '2020-09-03T01:03:55.4590' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

**Comment by BehindTheBrain** [comment]
$ pip3 install --upgrade assigner --user
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
Requirement already up-to-date: assigner in /home/user/.local/lib/python3.8/site-packages (2.0.1)
Requirement already satisfied, skipping upgrade: PyYAML>=3.13 in /usr/lib64/python3.8/site-packages (from assigner) (5.3.1)
Requirement already satisfied, skipping upgrade: PTable>=0.9 in /home/user/.local/lib/python3.8/site-packages (from assigner) (0.9.2)
Requirement already satisfied, skipping upgrade: colorlog<3,>=2.6 in /home/user/.local/lib/python3.8/site-packages (from assigner) (2.10.0)
Requirement already satisfied, skipping upgrade: enlighten>=1.5.0 in /usr/lib/python3.8/site-packages (from assigner) (1.6.0)
Requirement already satisfied, skipping upgrade: redkyn-common>=1.0.1 in /home/user/.local/lib/python3.8/site-packages (from assigner) (1.0.1)
Requirement already satisfied, skipping upgrade: jsonschema>=2.5 in /usr/lib/python3.8/site-packages (from assigner) (3.2.0)
Requirement already satisfied, skipping upgrade: requests>=2.20.0 in /usr/lib/python3.8/site-packages (from assigner) (2.22.0)
Requirement already satisfied, skipping upgrade: GitPython>=2.1.8 in /usr/lib/python3.8/site-packages (from assigner) (3.0.2)
Requirement already satisfied, skipping upgrade: blessed>=1.17.7 in /usr/lib/python3.8/site-packages (from enlighten>=1.5.0->assigner) (1.17.8)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /usr/lib/python3.8/site-packages (from jsonschema>=2.5->assigner) (19.3.0)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in /usr/lib64/python3.8/site-packages (from jsonschema>=2.5->assigner) (0.16.0)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3.8/site-packages (from jsonschema>=2.5->assigner) (41.6.0)
Requirement already satisfied, skipping upgrade: six>=1.11.0 in /usr/lib/python3.8/site-packages (from jsonschema>=2.5->assigner) (1.14.0)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests>=2.20.0->assigner) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3.8/site-packages (from requests>=2.20.0->assigner) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests>=2.20.0->assigner) (1.25.7)
Requirement already satisfied, skipping upgrade: gitdb2>=2.0.0 in /usr/lib/python3.8/site-packages (from GitPython>=2.1.8->assigner) (2.0.3)
Requirement already satisfied, skipping upgrade: wcwidth>=0.1.4 in /usr/lib/python3.8/site-packages (from blessed>=1.17.7->enlighten>=1.5.0->assigner) (0.2.4)
Requirement already satisfied, skipping upgrade: smmap2>=2.0.0 in /usr/lib/python3.8/site-packages (from gitdb2>=2.0.0->GitPython>=2.1.8->assigner) (2.0.3)

**Comment by LinuxMercedes** [comment]
This is probably due to a Gitlab upgrade that's changed their time formatting. I'll look at it in the morning and see what's up; this isn't the first time this has happened.
________________________________
