### ISSUE TITLE
commit -S adds but does not commit?

### ISSUE THREAD

**Issue by BehindTheBrain** [redkyn/assigner#160]
When making edits to a live assignment, by:

1. assigner lock assignment_n
2. assigner get assignment_n student_submissions
3. modify all student repos

`assigner commit -S assignment_n "message" student_submissions -u -a '*'` will add but not commit to student repos. It does sign.

But

`assigner commit assignment_name "message" student_submissions -u -a '*'` will add and commit

**Comment by LinuxMercedes** [comment]
I'm confused — what does `assigner commit -S` sign if it doesn't make a new commit?

**Comment by BehindTheBrain** [comment]
Yea, so I should have phrased that better. When one runs assigner commit repeatedly, it will make logged commits, regardless of whether there have been any changes. When one runs assigner commit -S it makes a change-less logged commit, just not one with any of the file edits (and it leaves the added changes queued up and green).

**Comment by LinuxMercedes** [comment]
Ahh, that makes sense. I'll take a look at it shortly; got my comprehensive exam coming up first though.
