### ISSUE TITLE
Canvas import imports student ID as username

### ISSUE THREAD

**Issue by HenryCWong** [redkyn/assigner#169]
After running `assigner canvas import <course ID> <section letter>` I saw in the _config.yml file that instead of the student's actual username their student id was in place. 

So when I create the git repos I think assigner is trying to add them based on their student ids, which it cannot find.

**Comment by LinuxMercedes** [comment]
It looks like Canvas changed the name for the SSO username column. I'll put together a fix shortly. Thanks!
