### ISSUE TITLE
Config validator is TOO VERBOSE

### ISSUE THREAD

**Issue by LinuxMercedes** [redkyn/assigner#17]
Seriously, it's crazy. 

Also, if you leave a key out (say, if you're setting stuff via config), you have to run each config command twice?

**Comment by michaelwisely** [comment]
The jsonschema thing?

Maybe it should just print "shame on you" and fail.

**Comment by LinuxMercedes** [comment]
Yeah I'm fine with saying "these things are missing". 

I'm less fine with 30 lines of error printed out while I'm just trying to set the config =|

**Comment by LinuxMercedes** [comment]
Fixed in #21
