### ISSUE TITLE
Subcommand to display a table with student project info

### ISSUE THREAD

**Issue by michaelwisely** [redkyn/assigner#2]
Each row is a student. Columns are...
- Student name
- Student ID (single sign on)
- Most recent (`HEAD`) commit on `master`
- Whether the student has been granted permission to the project
- Whether the project is locked for the student

[PrettyTable](https://pypi.python.org/pypi/PrettyTable) would be perfect for this.

Also `--student=id` (or something) would be handy for filtering.

**Comment by LinuxMercedes** [comment]
Maybe we should make this the `status` command?
