### ISSUE TITLE
Incorrect message displayed when assigning to an existing repo

### ISSUE THREAD

**Issue by islamelnabarawy** [redkyn/assigner#30]
**Severity:** Minimal
**Priority:** Low
### Issue Description

When attempting to use the `assign` command on an existing repository, even with only the master branch, `assigner` will attempt to push anyway. If the student has already pushed to the repository, the push will be rejected, but no error messages will be displayed for that repository. It will always display two messages similar to the following:

`INFO     2016FS-X-testdummy-ie3md: Already exists.`
`INFO     Pushed testdummy to 2016FS-X-testdummy-ie3md.`
#### Developer note:

I've traced this to the if branch at `assigner.py:107`, where `elif branch` will always be true, since branch is either a specified branch or "master" (see `assigner.py:52` - `assigner.py:55`). The `push_to()` code at `baserepo.py:317` does not check the result of the push and always displays the second information message above.
### Steps to reproduce:
1. `assigner new testdummy`
2. Clone the assignment repository, then create, commit, and push any file (e.g. `README.md`)
3. `assigner assign testdummy --student <your student ID>`
4. Clone the student repository, then create, commit, and push any dummy file (e.g. `dummy.txt`)
5. Go back to the assignment repository, and create, commit, then push another dummy file (e.g. `test.txt`)
6. Re-run the `assigner assign ...` command.
#### Actual Result:

You will receive messages similar to the following: 

`INFO     2016FS-X-testdummy-<your student ID>: Already exists.`
`INFO     Pushed testdummy to 2016FS-X-testdummy-<your student ID>.`

However, no actual changes will be pushed to the student repository.
#### Expected Result:

Either the push is skipped with an appropriate warning message, or the push results are checked and the actual push failure message is displayed.

**Comment by islamelnabarawy** [comment]
**Note:** An easy fix for this would be to change the line `assigner.py:107` to be `elif args.branch:`. That will cause the repository to be skipped every time, unless the `--force` option is specified.

**Comment by LinuxMercedes** [comment]
Yeah, the comment on `assigner.py:109` is wrong as things are written now. Your fix sounds right...let's go with that.
