### ISSUE TITLE
Import students directly from Joes'SS HTML table export

### ISSUE THREAD

**Issue by LinuxMercedes** [redkyn/assigner#4]
I think you have to use BeautifulSoup or something for this. 

Peoplesoft is amazing, in the worst way.

**Comment by LinuxMercedes** [comment]
`import` kind of works for this now. You have to export the table from Joes'SS, open it in Excel/free Excel, save as a .csv, then import it into assigner.

**Comment by islamelnabarawy** [comment]
Since Canvas will become the only LMS by the end of this year, it might be worth considering replacing the current `import` command with what is currently `canvas_import` at some point. It is much cleaner and more reliable.

**Comment by LinuxMercedes** [comment]
Yep, that sounds reasonable.

I'd like to rearchitect this so we could reasonably have plugins for peoplesoft and canvas and other LMS tools, as well as other tools -- maybe online grading software, or `grader` integration. I'd move `import` to be `csv import`; maybe we could get a `csv export` as well, and some way to map columns to fields. That's a ways down the road though.

**Comment by LinuxMercedes** [comment]
Don't think anyone has used the csv importing feature in years now and that's certainly for the best.
