### ISSUE TITLE
`init` command?

### ISSUE THREAD

**Issue by michaelwisely** [redkyn/assigner#44]
Something that can generate a shell config?

I am v lazy.

**Comment by LinuxMercedes** [comment]
I was thinking `setup` but yeah, something that could either take options on the command line or interact with you to get relevant data. I'd prefer the latter, at least for the tokens, since command-line args are visible in `ps` and in `.bash_history`.

**Comment by michaelwisely** [comment]
I was thinking of something more like `git init`, where it would just drop a basic config, which you can edit yourself or use `assigner config` to modify.

**Comment by LinuxMercedes** [comment]
The problem with that is that a basic config is `{}`. Everything the config contains needs to be set by the user?

**Comment by michaelwisely** [comment]
Ah, right. Sphinx does an interactive setup that's pretty nice. We could just use the example config to offer default values (like `deadbeef` for your GitLab). That way users can just slap Enter if they don't know values offhand.

**Comment by LinuxMercedes** [comment]
Yeah that sounds pretty reasonable.
