### ISSUE TITLE
Multiply-imported kids

### ISSUE THREAD

**Issue by michaelwisely** [redkyn/assigner#46]
Running `canvas_import` more than once seems to duplicate students.

**Comment by LinuxMercedes** [comment]
Are they duplicated within the same section, or across two sections? The former is a bug; the latter I'm OK with, I think. For example, if a student switches sections midway through an assignment, you'd need to be able to `get` his submission for one section while having him exist in another?

**Comment by islamelnabarawy** [comment]
I think it's a bug, I don't think there's any code in there to check if a user already exists before adding it to the config file. I was planning on eventually improving the command to "update" the section such that new users would be added and missing users would be removed.
