### ISSUE TITLE
Docs Website

### ISSUE THREAD

**Issue by LinuxMercedes** [redkyn/assigner#50]
Assigner is getting complicated enough that we should work on getting a docs website with tutorials, command documentation, and internals documentation set up. We should probably mirror how grader does it with some beautiful ReStructured Text and a generated website.

**Comment by michaelwisely** [comment]
I can get a shell Sphinx site setup, at least. It shouldn't be hard to publish it to readthedocs if we wanted that.

**Comment by LinuxMercedes** [comment]
`TUTORIAL.md` is going to have to do for now.
