### ISSUE TITLE
`assigner new` should provide SSH git url instead of HTTPS

### ISSUE THREAD

**Issue by LinuxMercedes** [redkyn/assigner#53]
Or it could provide both..either way, I'm tired of hand-mangling the url into something I don't have to type my password for.

**Comment by michaelwisely** [comment]
Can we check if there is an SSH key setup? It'd be neat if it used SSH when it was there, and used HTTPS as a fallback.

**Comment by LinuxMercedes** [comment]
I don't know that we can know that--it's possible that they have a key for a different machine in their gitlab account, or something else. We could just print both URLs...that wouldn't be terrible.

**Comment by michaelwisely** [comment]
FWIW, it looks like we can see if the authenticated user has any [SSH keys](https://docs.gitlab.com/ce/api/users.html#list-ssh-keys) associated with their account. You're right though. If you're on a different box that doesn't have a key (or something), it would be handy to have both links.
