### ISSUE TITLE
Protect + developer push

### ISSUE THREAD

**Issue by michaelwisely** [redkyn/assigner#56]
I like to protect the master branch to preclude any `push -f` nonsense from clever (or not so) students. It appears that GitLab's API [defaults to `developers_can_push=false`](https://docs.gitlab.com/ce/api/branches.html#protect-repository-branch). It would be nice if we could specify whether or not developers are allowed to push.

If I *proper* protect their branches (no students push) and I later decide that I want to unprotect them, I would prefer to put them back to protected+developers_can_push rather than completely unprotected.

So

~~~shell
$ assigner protect  # Lock them outta that biz
$ # Get in there; get what's good; be on my way
$ assigner protect --developers-can-push  # They can push again; still can't force push
~~~

[Relevant link](https://youtu.be/Oe17RymMqWI?t=28s)

**Comment by LinuxMercedes** [comment]
Isn't that what [lock](https://github.com/redkyn/assigner/blob/master/commands/lock.py) is for?

I should probably turn off the default-unprotect option since I do agree that usually we don't want to let people force push to master.

**Comment by michaelwisely** [comment]
Ah, yep.

Yeah, I would guess in most cases disallowing forced​ pushes would be
preferred.

I've also run into a couple of instances where it's useful to permit forced
pushes prior to opening the assignment (and forbidding them again later). I
suppose I could have `assign --force`d those, but I find sometimes it's
easier to perform my own git magic to fix my mistakes.

Maybe a master can force push to a protected branch when developers can't?
I think I need to have another look at the docs...

On Apr 3, 2017 4:50 PM, "LinuxMercedes" <notifications@github.com> wrote:

Isn't that what lock
<https://github.com/redkyn/assigner/blob/master/commands/lock.py> is for?

I should probably turn off the default-unprotect option since I do agree
that usually we don't want to let people force push to master.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/redkyn/assigner/issues/56#issuecomment-291284766>, or mute
the thread

**Comment by LinuxMercedes** [comment]
How about we unprotect branches in `assign`, but protect them by default in `open`? That way you can `push -f` before your students have access to the repo. I'd say that if you're force pushing after giving them access you probably need to reconsider your life choices...

**Comment by michaelwisely** [comment]
Heh, yeah. Just `push -f` and reset them all back to the starter code 😆 

I think your earlier suggestion for `unprotect` to default to protecting master with `developers_can_push=true` would be sufficient. Most of the time (in my experience at least) there's no need to force push to their repos at all.
