### ISSUE TITLE
Complete Features

### ISSUE THREAD

**Issue by LinuxMercedes** [redkyn/assigner#7]
- [x] `assign --dry-run`
- [x] `assign --student`
- [x] `get --student`
- [x] `(un)lock --student`
- [ ] `(un)lock --dry-run`
- [x] `status`

**Comment by islamelnabarawy** [comment]
`assign --student` was also implemented by #27 

What is exact expected behavior of the `--dry-run` option for the `lock`/`unlock` commands?

**Comment by LinuxMercedes** [comment]
`--dry-run` shows the result of running lock/unlock, but doesn't actually change anything. Basically everything except the actual call to the GitLab API to perform the action.
