### ISSUE TITLE
Create a proper BaseRepo backend which is API agnostic. Make Gitlab an implementation.

### ISSUE THREAD

**Issue by brhoades** [redkyn/assigner#95]
Edit:
In `baserepo.py`, there are three primary classes: `BaseRepo`, `Repo`, and `StudentRepo`. Those three classes form a backend for interfacing with Gitlab.

Let's make `BaseRepo` an abstract base of `Repo` and house it in `backends/base.py`. Additionally, let's add `BaseStudentRepo` which is a `BaseRepo` that's an abstract base for `StudentRepo`. We can also define the `BaseBackend` in this file which is an abstract base for a backend. `BaseBackend`, for now, will contain generically named class variables (such as `student_repo` and `repo`) so that assigner commands can be agnostic of the backend. Later this backend can do more fancy stuff.

Our current `Repo` and `StudentRepo` can then be implementations of `BaseRepo` and `BaseStudentRepo` respectively. They can be housed in `backends/gitlab.py`. A new `GitlabBackend` (`BaseBackend`) will also need to be created.

**Comment by LinuxMercedes** [comment]
Frankly, we really ought to split the GitLab and Git parts of `BaseRepo`...at the very least, I will make a helper GitLab module because #87 will also need to hit the GitLab API without a "repository" associated.

**Comment by brhoades** [comment]
I agree, BaseRep has too much meat.

**Comment by brhoades** [comment]
@LinuxMercedes changed the scope of this issue. Seems pretty doable. Thoughts?
