### ISSUE TITLE
Add, commit, and push any existing additions to all student repos for a given project?

### ISSUE THREAD

**Issue by BehindTheBrain** [redkyn/assigner#98]
For example, we may want to run an autograder locally that drops a feedback file in each student directory that would be good to push back to them in batch.

**Comment by LinuxMercedes** [comment]
Yep, I like this -- maybe `assigner push`?

(FYI, `assigner get` clones complete git repos, so if you make your autograder git-aware, it can do this right now by itself. But, I do agree that having Assigner be able to do this would be nicer.)

**Comment by BehindTheBrain** [comment]
Yes, assigner push is great. Thanks for the suggestion that we could write a grader to do it -- thanks.

I actually thing you guys have something here, that with a bit more generalization, could have much wider appeal. That is, an app for n-repository operations and management; many of the basics are there already. I'm imagining this might be quite useful for companies managing big sets of repos for developers, managing coding competitions, and the obvious current use for classrooms. Does that not exist in general form?

**Comment by LinuxMercedes** [comment]
I haven't seen or heard of any such tool. I have found a couple other projects like this, but they seem to be mostly unmaintained and tied to GitHub.

@brhoades is working (see PR #102) on abstracting Assigner's backend so we could use it with just about any GitLab-like website (provided someone wrote the appropriate glue code).
